# Generated by Django 4.2.27 on 2026-02-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_created_date_author_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_best_sell',
            field=models.BooleanField(default=False),
        ),
    ]
